[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Ryan Bauer <ryanemilbauer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
num-traits = "0.2"
approx = "0.3.2"

